/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_scut_cs_sysm_hello_Hello */

#ifndef _Included_edu_scut_cs_sysm_hello_Hello
#define _Included_edu_scut_cs_sysm_hello_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_scut_cs_sysm_hello_Hello
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_sysm_hello_Hello_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
