/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_scut_cs_hbdc_sysm_Sysm */

#ifndef _Included_edu_scut_cs_hbdc_sysm_Sysm
#define _Included_edu_scut_cs_hbdc_sysm_Sysm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    getNativeLibVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_getNativeLibVersion
  (JNIEnv *, jclass);

/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    nativeOpen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_nativeOpen
  (JNIEnv *, jobject);

/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    nativeClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    signal
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_signal
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    getPid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_getPid
  (JNIEnv *, jobject);

/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    getCpuInfos
 * Signature: ()[Ledu/scut/cs/hbdc/sysm/bean/CpuInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_getCpuInfos
  (JNIEnv *, jobject);

/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    getCpusNative
 * Signature: ()[Ledu/scut/cs/hbdc/sysm/bean/Cpu;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_getCpusNative
  (JNIEnv *, jobject);

/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    getLoadAverage
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_getLoadAverage
  (JNIEnv *, jobject);

/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    getProcesses
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_getProcesses
  (JNIEnv *, jobject);

/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    getProcessArgs
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_getProcessArgs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    getProcessPort
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_getProcessPort
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    getNetRoutes
 * Signature: ()[Ledu/scut/cs/hbdc/sysm/bean/NetRoute;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_getNetRoutes
  (JNIEnv *, jobject);

/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    getNetInterfaces
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_getNetInterfaces
  (JNIEnv *, jobject);

/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    getNetConnections
 * Signature: (I)[Ledu/scut/cs/hbdc/sysm/bean/NetConnection;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_getNetConnections
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    getNetListenAddress
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_getNetListenAddress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_scut_cs_hbdc_sysm_Sysm
 * Method:    getWhos
 * Signature: ()[Ledu/scut/cs/hbdc/sysm/bean/Who;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_scut_cs_hbdc_sysm_Sysm_getWhos
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_Memory */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_Memory
#define _Included_edu_scut_cs_hbdc_sysm_bean_Memory
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_Memory_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_Memory_serialVersionUID -1415576389011166337i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_Memory
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_Memory_gather
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_Swap */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_Swap
#define _Included_edu_scut_cs_hbdc_sysm_bean_Swap
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_Swap_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_Swap_serialVersionUID 5218483109795811484i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_Swap
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_Swap_gather
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_Cpu */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_Cpu
#define _Included_edu_scut_cs_hbdc_sysm_bean_Cpu
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_Cpu_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_Cpu_serialVersionUID 5216973339055138142i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_Cpu
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_Cpu_gather
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_CpuPercentage */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_CpuPercentage
#define _Included_edu_scut_cs_hbdc_sysm_bean_CpuPercentage
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_CpuPercentage_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_CpuPercentage_serialVersionUID 1801343789274322897i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_CpuPercentage
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;Ledu/scut/cs/hbdc/sysm/bean/Cpu;Ledu/scut/cs/hbdc/sysm/bean/Cpu;)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_CpuPercentage_gather
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_Uptime */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_Uptime
#define _Included_edu_scut_cs_hbdc_sysm_bean_Uptime
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_Uptime_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_Uptime_serialVersionUID 6663306996690896859i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_Uptime
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_Uptime_gather
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_ProcessCpu */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_ProcessCpu
#define _Included_edu_scut_cs_hbdc_sysm_bean_ProcessCpu
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_ProcessCpu_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_ProcessCpu_serialVersionUID 1870673427995892017i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_ProcessCpu
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;J)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_ProcessCpu_gather
  (JNIEnv *, jobject, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_ProcessEnv */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_ProcessEnv
#define _Included_edu_scut_cs_hbdc_sysm_bean_ProcessEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_ProcessEnv
 * Method:    getAll
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;J)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_edu_scut_cs_hbdc_sysm_bean_ProcessEnv_getAll
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_ProcessEnv
 * Method:    getValue
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_scut_cs_hbdc_sysm_bean_ProcessEnv_getValue
  (JNIEnv *, jclass, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_ProcessExe */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_ProcessExe
#define _Included_edu_scut_cs_hbdc_sysm_bean_ProcessExe
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_ProcessExe_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_ProcessExe_serialVersionUID -8037854520893715933i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_ProcessExe
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;J)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_ProcessExe_gather
  (JNIEnv *, jobject, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_ProcessMem */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_ProcessMem
#define _Included_edu_scut_cs_hbdc_sysm_bean_ProcessMem
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_ProcessMem_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_ProcessMem_serialVersionUID 4295190486462289477i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_ProcessMem
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;J)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_ProcessMem_gather
  (JNIEnv *, jobject, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_ProcessOwn */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_ProcessOwn
#define _Included_edu_scut_cs_hbdc_sysm_bean_ProcessOwn
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_ProcessOwn_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_ProcessOwn_serialVersionUID 2125414655040821585i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_ProcessOwn
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;J)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_ProcessOwn_gather
  (JNIEnv *, jobject, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_ProcessOwner */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_ProcessOwner
#define _Included_edu_scut_cs_hbdc_sysm_bean_ProcessOwner
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_ProcessOwner_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_ProcessOwner_serialVersionUID 467731875357745897i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_ProcessOwner
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;J)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_ProcessOwner_gather
  (JNIEnv *, jobject, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_ProcessStat */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_ProcessStat
#define _Included_edu_scut_cs_hbdc_sysm_bean_ProcessStat
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_ProcessStat_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_ProcessStat_serialVersionUID -1262624303422210931i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_ProcessStat
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_ProcessStat_gather
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_ProcessState */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_ProcessState
#define _Included_edu_scut_cs_hbdc_sysm_bean_ProcessState
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_ProcessState_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_ProcessState_serialVersionUID 6682856328296314457i64
#undef edu_scut_cs_hbdc_sysm_bean_ProcessState_SLEEP
#define edu_scut_cs_hbdc_sysm_bean_ProcessState_SLEEP 83L
#undef edu_scut_cs_hbdc_sysm_bean_ProcessState_RUN
#define edu_scut_cs_hbdc_sysm_bean_ProcessState_RUN 82L
#undef edu_scut_cs_hbdc_sysm_bean_ProcessState_STOP
#define edu_scut_cs_hbdc_sysm_bean_ProcessState_STOP 84L
#undef edu_scut_cs_hbdc_sysm_bean_ProcessState_ZOMBIE
#define edu_scut_cs_hbdc_sysm_bean_ProcessState_ZOMBIE 90L
#undef edu_scut_cs_hbdc_sysm_bean_ProcessState_IDLE
#define edu_scut_cs_hbdc_sysm_bean_ProcessState_IDLE 68L
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_ProcessState
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;J)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_ProcessState_gather
  (JNIEnv *, jobject, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_ProcessTime */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_ProcessTime
#define _Included_edu_scut_cs_hbdc_sysm_bean_ProcessTime
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_ProcessTime_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_ProcessTime_serialVersionUID -3725565335469224312i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_ProcessTime
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;J)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_ProcessTime_gather
  (JNIEnv *, jobject, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_ResourceLimit */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_ResourceLimit
#define _Included_edu_scut_cs_hbdc_sysm_bean_ResourceLimit
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_ResourceLimit_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_ResourceLimit_serialVersionUID -666385672071329561i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_ResourceLimit
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_ResourceLimit_gather
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_DiskUsage */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_DiskUsage
#define _Included_edu_scut_cs_hbdc_sysm_bean_DiskUsage
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_DiskUsage_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_DiskUsage_serialVersionUID 5588698372036871730i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_DiskUsage
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_DiskUsage_gather
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_NetInfo */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_NetInfo
#define _Included_edu_scut_cs_hbdc_sysm_bean_NetInfo
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_NetInfo_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_NetInfo_serialVersionUID 607069717891507718i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_NetInfo
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_NetInfo_gather
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_NetStat */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_NetStat
#define _Included_edu_scut_cs_hbdc_sysm_bean_NetStat
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_NetStat_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_NetStat_serialVersionUID 8431951154960807027i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_NetStat
 * Method:    stat
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;I[BJ)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_NetStat_stat
  (JNIEnv *, jobject, jobject, jint, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_NetInterfaceConfig */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_NetInterfaceConfig
#define _Included_edu_scut_cs_hbdc_sysm_bean_NetInterfaceConfig
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_NetInterfaceConfig_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_NetInterfaceConfig_serialVersionUID 7301426444308634132i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_NetInterfaceConfig
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_NetInterfaceConfig_gather
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_scut_cs_hbdc_sysm_bean_NetInterfaceStat */

#ifndef _Included_edu_scut_cs_hbdc_sysm_bean_NetInterfaceStat
#define _Included_edu_scut_cs_hbdc_sysm_bean_NetInterfaceStat
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_scut_cs_hbdc_sysm_bean_NetInterfaceStat_serialVersionUID
#define edu_scut_cs_hbdc_sysm_bean_NetInterfaceStat_serialVersionUID -6283383811559689540i64
/*
 * Class:     edu_scut_cs_hbdc_sysm_bean_NetInterfaceStat
 * Method:    gather
 * Signature: (Ledu/scut/cs/hbdc/sysm/Sysm;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_scut_cs_hbdc_sysm_bean_NetInterfaceStat_gather
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
